# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd56a43e0b43b3822d860904954467664197e6efee088882e9068374297e0a797b4a90c6ff75893ed8e93cd013be0ded1e1ec90e9d8747b02619815398d5186e

test:
  secret_key_base: eed59704923235cbb20bfdff7d2bb15cc91f624c6e02a931eaf7baef030699c481670f31738ea55497089d1ca1ab28a5c02f7f14fb08c8d44c120130dc76c18a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
